-- Secondary Green Lab database.
-- Derived from the application contract in the green-lab-attendance repository.
-- This migration is for the secondary Supabase project only.

create extension if not exists pg_cron;

create table if not exists public.lab_students (
  id bigint generated by default as identity primary key,
  student_code text not null unique,
  full_name text not null,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lab_devices (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.lab_students(id) on delete cascade,
  device_token text not null unique,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz,
  is_active boolean not null default true
);

create index if not exists idx_lab_devices_student
  on public.lab_devices(student_id);

create table if not exists public.lab_attendance (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.lab_students(id) on delete cascade,
  device_id bigint references public.lab_devices(id) on delete set null,
  entry_at timestamptz not null default now(),
  expires_at timestamptz not null,
  exit_at timestamptz,
  duration_minutes integer,
  exit_mode text check (exit_mode is null or exit_mode in ('manual','automatic')),
  entry_source text check (entry_source is null or entry_source in ('web','qr')),
  created_at timestamptz not null default now(),
  constraint lab_attendance_duration_nonnegative
    check (duration_minutes is null or duration_minutes >= 0),
  constraint lab_attendance_exit_after_entry
    check (exit_at is null or exit_at >= entry_at),
  constraint lab_attendance_expiry_after_entry
    check (expires_at >= entry_at)
);

create index if not exists idx_lab_attendance_student
  on public.lab_attendance(student_id, id desc);

create index if not exists idx_lab_attendance_active_expiry
  on public.lab_attendance(expires_at)
  where exit_at is null;

create or replace function public.lab_touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  new.updated_at := clock_timestamp();
  return new;
end;
$function$;

drop trigger if exists trg_lab_students_updated_at on public.lab_students;
create trigger trg_lab_students_updated_at
before update on public.lab_students
for each row execute function public.lab_touch_updated_at();

create or replace function public.lab_register_device(
  p_student_code text,
  p_full_name text,
  p_device_token text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_user_id uuid := auth.uid();
  v_student public.lab_students%rowtype;
  v_device public.lab_devices%rowtype;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;
  if p_student_code is null or btrim(p_student_code) = ''
     or p_full_name is null or btrim(p_full_name) = ''
     or p_device_token is null or btrim(p_device_token) = '' then
    raise exception 'student_code, full_name and device_token are required';
  end if;
  if length(p_device_token) > 200 then raise exception 'Invalid device token'; end if;

  select * into v_device
  from public.lab_devices
  where device_token = btrim(p_device_token)
  limit 1;

  if found then
    select * into v_student from public.lab_students where id = v_device.student_id limit 1;
    if v_student.auth_user_id is distinct from v_user_id then
      raise exception 'This device is already registered to another student';
    end if;
    update public.lab_devices
       set last_seen_at = clock_timestamp(), is_active = true
     where id = v_device.id;
    return jsonb_build_object(
      'student_code', v_student.student_code,
      'name', v_student.full_name,
      'device_registered', true,
      'already_registered', true
    );
  end if;

  select * into v_student
  from public.lab_students
  where student_code = btrim(p_student_code)
  limit 1;

  if found then
    if v_student.auth_user_id is not null
       and v_student.auth_user_id is distinct from v_user_id then
      raise exception 'Student ID is already registered to another account';
    end if;
    if not v_student.is_active then raise exception 'Student account is inactive'; end if;
    if v_student.auth_user_id is null then
      update public.lab_students
         set auth_user_id = v_user_id, full_name = btrim(p_full_name)
       where id = v_student.id
       returning * into v_student;
    end if;
  else
    insert into public.lab_students(student_code, full_name, auth_user_id)
    values (btrim(p_student_code), btrim(p_full_name), v_user_id)
    returning * into v_student;
  end if;

  insert into public.lab_devices(student_id, device_token, last_seen_at)
  values (v_student.id, btrim(p_device_token), clock_timestamp());

  return jsonb_build_object(
    'student_code', v_student.student_code,
    'name', v_student.full_name,
    'device_registered', true,
    'already_registered', false
  );
end;
$function$;

create or replace function public.lab_student_by_device(p_device_token text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_student public.lab_students%rowtype;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;

  select s.* into v_student
  from public.lab_devices d
  join public.lab_students s on s.id = d.student_id
  where d.device_token = p_device_token
    and d.is_active
    and s.is_active
    and s.auth_user_id = auth.uid()
  limit 1;

  if not found then return null; end if;

  update public.lab_devices
     set last_seen_at = clock_timestamp()
   where device_token = p_device_token;

  return jsonb_build_object(
    'student_code', v_student.student_code,
    'student_id', v_student.id,
    'name', v_student.full_name
  );
end;
$function$;

create or replace function public.lab_expire_attendance()
returns integer
language plpgsql
security definer
set search_path = ''
as $function$
declare v_count integer;
begin
  update public.lab_attendance
     set exit_at = expires_at,
         duration_minutes = greatest(0, floor(extract(epoch from (expires_at - entry_at)) / 60))::integer,
         exit_mode = 'automatic'
   where exit_at is null and expires_at <= clock_timestamp();

  get diagnostics v_count = row_count;
  return v_count;
end;
$function$;

create or replace function public.lab_attendance_current(p_device_token text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_student public.lab_students%rowtype;
  v_device public.lab_devices%rowtype;
  v_session public.lab_attendance%rowtype;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  perform public.lab_expire_attendance();

  select * into v_device
  from public.lab_devices
  where device_token = p_device_token
  limit 1;

  if not found then raise exception 'Device is not registered'; end if;

  select * into v_student
  from public.lab_students
  where id = v_device.student_id
    and auth_user_id = auth.uid()
    and is_active
  limit 1;

  if not found then raise exception 'Student/device registration not found'; end if;

  select * into v_session
  from public.lab_attendance
  where student_id = v_student.id and exit_at is null
  order by id desc
  limit 1;

  if not found then
    return jsonb_build_object(
      'inside_lab', false,
      'student_code', v_student.student_code,
      'name', v_student.full_name,
      'session', null
    );
  end if;

  return jsonb_build_object(
    'inside_lab', true,
    'student_code', v_student.student_code,
    'name', v_student.full_name,
    'session', jsonb_build_object(
      'entry_time', v_session.entry_at,
      'expires_at', v_session.expires_at,
      'exit_time', v_session.exit_at,
      'duration_minutes', v_session.duration_minutes,
      'exit_mode', v_session.exit_mode,
      'entry_source', v_session.entry_source
    )
  );
end;
$function$;

create or replace function public.lab_attendance_entry(
  p_device_token text,
  p_entry_source text default 'web'
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_student public.lab_students%rowtype;
  v_device public.lab_devices%rowtype;
  v_active public.lab_attendance%rowtype;
  v_entry timestamptz;
  v_expires timestamptz;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if p_entry_source is not null and p_entry_source not in ('web','qr') then
    raise exception 'Invalid entry source';
  end if;

  perform public.lab_expire_attendance();

  select * into v_device
  from public.lab_devices
  where device_token = p_device_token and is_active
  limit 1;
  if not found then raise exception 'Device is not registered'; end if;

  select * into v_student
  from public.lab_students
  where id = v_device.student_id
    and auth_user_id = auth.uid()
    and is_active
  limit 1;
  if not found then raise exception 'Student/device registration not found'; end if;

  select * into v_active
  from public.lab_attendance
  where student_id = v_student.id and exit_at is null
  order by id desc
  limit 1
  for update;
  if found then raise exception 'You are already inside Green Lab'; end if;

  v_entry := clock_timestamp();
  v_expires := v_entry + interval '2 hours';

  insert into public.lab_attendance(
    student_id, device_id, entry_at, expires_at, entry_source
  )
  values (
    v_student.id, v_device.id, v_entry, v_expires, coalesce(p_entry_source, 'web')
  );

  update public.lab_devices set last_seen_at = v_entry where id = v_device.id;

  return jsonb_build_object(
    'action', 'entry',
    'student_code', v_student.student_code,
    'name', v_student.full_name,
    'entry_time', v_entry,
    'expires_at', v_expires
  );
end;
$function$;

create or replace function public.lab_attendance_exit(p_device_token text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_student public.lab_students%rowtype;
  v_device public.lab_devices%rowtype;
  v_session public.lab_attendance%rowtype;
  v_now timestamptz;
  v_exit_mode text;
  v_exit_at timestamptz;
  v_duration integer;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  perform public.lab_expire_attendance();

  select * into v_device
  from public.lab_devices
  where device_token = p_device_token and is_active
  limit 1;
  if not found then raise exception 'Device is not registered'; end if;

  select * into v_student
  from public.lab_students
  where id = v_device.student_id
    and auth_user_id = auth.uid()
    and is_active
  limit 1;
  if not found then raise exception 'Student/device registration not found'; end if;

  select * into v_session
  from public.lab_attendance
  where student_id = v_student.id and exit_at is null
  order by id desc
  limit 1
  for update;
  if not found then raise exception 'No active entry found'; end if;

  v_now := clock_timestamp();

  if v_session.expires_at <= v_now then
    v_exit_at := v_session.expires_at;
    v_exit_mode := 'automatic';
  else
    v_exit_at := v_now;
    v_exit_mode := 'manual';
  end if;

  v_duration := greatest(0, floor(extract(epoch from (v_exit_at - v_session.entry_at)) / 60))::integer;

  update public.lab_attendance
     set exit_at = v_exit_at,
         duration_minutes = v_duration,
         exit_mode = v_exit_mode
   where id = v_session.id;

  update public.lab_devices set last_seen_at = v_now where id = v_device.id;

  return jsonb_build_object(
    'action', case when v_exit_mode = 'automatic' then 'automatic_exit' else 'manual_exit' end,
    'student_code', v_student.student_code,
    'name', v_student.full_name,
    'entry_time', v_session.entry_at,
    'exit_time', v_exit_at,
    'expires_at', v_session.expires_at,
    'duration_minutes', v_duration,
    'exit_mode', v_exit_mode,
    'entry_source', v_session.entry_source
  );
end;
$function$;

create or replace function public.lab_attendance_history(p_device_token text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_student public.lab_students%rowtype;
  v_history jsonb;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  perform public.lab_expire_attendance();

  select s.* into v_student
  from public.lab_devices d
  join public.lab_students s on s.id = d.student_id
  where d.device_token = p_device_token
    and d.is_active
    and s.auth_user_id = auth.uid()
  limit 1;
  if not found then raise exception 'Student/device registration not found'; end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'attendance_id', a.id,
        'student_code', v_student.student_code,
        'name', v_student.full_name,
        'entry_time', a.entry_at,
        'exit_time', a.exit_at,
        'expires_at', a.expires_at,
        'duration_minutes', a.duration_minutes,
        'exit_mode', a.exit_mode,
        'entry_source', a.entry_source
      )
      order by a.id desc
    ),
    '[]'::jsonb
  )
  into v_history
  from public.lab_attendance a
  where a.student_id = v_student.id;

  return v_history;
end;
$function$;

alter table public.lab_students enable row level security;
alter table public.lab_devices enable row level security;
alter table public.lab_attendance enable row level security;

drop policy if exists "lab students self read" on public.lab_students;
create policy "lab students self read"
on public.lab_students for select to authenticated
using (auth_user_id = auth.uid());

drop policy if exists "lab devices self read" on public.lab_devices;
create policy "lab devices self read"
on public.lab_devices for select to authenticated
using (
  exists (
    select 1 from public.lab_students s
    where s.id = lab_devices.student_id
      and s.auth_user_id = auth.uid()
  )
);

drop policy if exists "lab attendance self read" on public.lab_attendance;
create policy "lab attendance self read"
on public.lab_attendance for select to authenticated
using (
  exists (
    select 1 from public.lab_students s
    where s.id = lab_attendance.student_id
      and s.auth_user_id = auth.uid()
  )
);

revoke all on public.lab_students from anon, authenticated;
revoke all on public.lab_devices from anon, authenticated;
revoke all on public.lab_attendance from anon, authenticated;

revoke all on function public.lab_register_device(text,text,text) from public;
revoke all on function public.lab_student_by_device(text) from public;
revoke all on function public.lab_expire_attendance() from public;
revoke all on function public.lab_attendance_current(text) from public;
revoke all on function public.lab_attendance_entry(text,text) from public;
revoke all on function public.lab_attendance_exit(text) from public;
revoke all on function public.lab_attendance_history(text) from public;

grant execute on function public.lab_register_device(text,text,text) to authenticated;
grant execute on function public.lab_student_by_device(text) to authenticated;
grant execute on function public.lab_attendance_current(text) to authenticated;
grant execute on function public.lab_attendance_entry(text,text) to authenticated;
grant execute on function public.lab_attendance_exit(text) to authenticated;
grant execute on function public.lab_attendance_history(text) to authenticated;

do $schedule$
declare v_job_id bigint;
begin
  for v_job_id in
    select jobid from cron.job
    where jobname = 'green-lab-secondary-auto-exit'
  loop
    perform cron.unschedule(v_job_id);
  end loop;

  perform cron.schedule(
    'green-lab-secondary-auto-exit',
    '* * * * *',
    'select public.lab_expire_attendance();'
  );
end;
$schedule$;